### ISSUE TITLE
problem when make install

### ISSUE THREAD

**Issue by punjasin** [RehabMan/Lenovo-Y50-DSDT-Patch#5]
it said volumes/EFI/EFI/CLOVER/ACPI/patched/SSDT-HACK.aml: No such file or directory

**Comment by ddulic** [comment]
Did you mount the /EFI partition?

**Comment by punjasin** [comment]
i mount it but it not work i i have to copy and paste by myseft don't know it working or not too :( but thank

**Comment by RehabMan** [comment]
You forgot to install Clover.  Follow the guide as written.  Carefully.
