### ISSUE TITLE
Backlight control broken on 10.12.4

### ISSUE THREAD

**Issue by coderobe** [RehabMan/Lenovo-Y50-DSDT-Patch#7]
After the update to Sierra 10.12.4 the backlight control stopped doing anything.
The control still shows up:
![screen shot 2017-03-28 at 01 54 47](https://cloud.githubusercontent.com/assets/8442384/24382892/9d9cf9f8-1359-11e7-94a2-8d62c742e5ca.png)

and is still controllable, but it doesn't actually affect anything. The Display stays at full brightness.

**Comment by RehabMan** [comment]
Known issue with IntelBacklight.kext ATM.
See here: https://www.tonymacx86.com/threads/readme-common-some-unsolved-problems-in-10-12-sierra.202316/
