### ISSUE TITLE
Error: Volume "/" is not GPT disk or APFS container

### ISSUE THREAD

**Issue by BumbayBoy** [RehabMan/Lenovo-Y50-DSDT-Patch#9]
I created a 10.13.4 installation SSD APFS (Clone) from my MacBookPro
Put the ssd in the laptop I have to use my friends' EFI file everything is ok to reach the Desktop
I created the folder Projects / y50.git
at the commands step
cd ~/Projects/y50.git
./mount_efi.sh
I have an error.
**Error: Volume "/" is not GPT disk or APFS container**

Is being in 10.13.4 Beta a problem?

my ssd seems in good condition
![Modular Image Creation](http://www.hostpic.org/images/1801282219180092.png)

**Comment by RehabMan** [comment]
Use the forums:
https://www.tonymacx86.com/threads/guide-lenovo-y50-uhd-or-1080p-using-clover-uefi.232960/
